server:
    port: 3000
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ZJyW4agQBG93p6xlVTLDbBb1sQ1uOodj
            client-secret: S1iT709TWP4uBivQL3AJHf-7LbKT_CWEBNTnZxU4lOwnOD2rBLaRMgcS1ueITQwQ
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-porvrutu0wx0sqf5.us.auth0.com/

